on:
  push:
    branches: [ master ]
    tags:
      - v1.*

name: build

jobs:
  docs-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install

      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GH_PAT }}
          cname: developers.onli.com.br
